# Generated by Django 3.2.3 on 2021-06-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='baseusers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hashtagtrend',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
