# Generated by Django 3.2.4 on 2021-06-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0002_auto_20210615_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseusers',
            name='screen_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
